.TH  "kerberos_selinux"  "8"  "17 Янв 2005" "dwalsh@redhat.com" "kerberos Selinux Policy documentation"
.de EX
.nf
.ft CW
..
.de EE
.ft R
.fi
..
.SH "НАЗВАНИЕ"
kerberos_selinux \- Политика Security Enhanced Linux для Kerberos.
.SH "ОПИСАНИЕ"

Security-Enhanced Linux защищает систему при помощи гибко настраиваемого мандатного контроля доступа. По умолчанию Kerberos запрещен, поскольку требуется функционирование демонов,
которым предоставляется слишком обширный доступ к сети и некоторым чувствительным в плане безопасности файлам.

.SH ПЕРЕКЛЮЧАТЕЛИ (BOOLEANS)
.PP
Для того, чтобы система могла корректно работать в окружении Kerberos, вы должны установить переключатель allow_kerberos.
.EX
setsebool -P allow_kerberos 1
.EE
.PP
Для управления настройками SELinux существует графическая утилита system-config-selinux.
.SH АВТОРЫ	
Эту страницу руководства написал Dan Walsh <dwalsh@redhat.com>.
Перевод руководства - Андрей Маркелов <andrey@markelov.net>, 2007г.

.SH "СМОТРИ ТАКЖЕ"
selinux(8), kerberos(1), chcon(1), setsebool(8)
