.TH  "named_selinux"  "8"  "17 Янв 2005" "dwalsh@redhat.com" "named Selinux Policy documentation"
.de EX
.nf
.ft CW
..
.de EE
.ft R
.fi
..
.SH "НАЗВАНИЕ"
named_selinux \- Политика Security Enhanced Linux для демона Internet Name server (named)
.SH "ОПИСАНИЕ"

Security-Enhanced Linux обеспечивает защиту сервера named при помощи гибко настраиваемого мандатного контроля доступа.
.SH ПЕРЕКЛЮЧАТЕЛИ (BOOLEANS)
Политика SELinux настраивается исходя из принципа наименьших привилегий. Таким образом,
по умолчанию политика SELinux не позволяет демону named осуществлять изменения файлов мастер-зоны.
Если вам необходимо, чтобы named мог обновлять файлы мастер-зоны, вы должны установить переключатель named_write_master_zones boolean.
.EX
setsebool -P named_write_master_zones 1
.EE
.PP
Для управления настройками SELinux существует графическая утилита system-config-selinux.
.SH АВТОРЫ	
Эту страницу руководства написал Dan Walsh <dwalsh@redhat.com>.
Перевод руководства - Андрей Маркелов <andrey@markelov.net>, 2007г.

.SH "СМОТРИ ТАКЖЕ"
selinux(8), named(8), chcon(1), setsebool(8)


