.TH  "nfs_selinux"  "8"  "17 Янв 2005" "dwalsh@redhat.com" "nfs Selinux Policy documentation"
.SH "НАЗВАНИЕ"
nfs_selinux \- Политика Security Enhanced Linux для NFS
.SH "ОПИСАНИЕ"

Security-Enhanced Linux защищает сервер nfs при помощи гибко настраиваемого мандатного контроля доступа.
.SH ПЕРЕКЛЮЧАТЕЛИ (BOOLEANS)
Политика SELinux настраивается исходя из принципа наименьших привилегий. Таким образом, 
по умолчанию политика SELinux не позволяет предоставлять доступ к файлам по nfs. Если вы хотите 
разрешить доступ только на чтение к файлам этой машины по nfs, вы должны установить переключатель
nfs_export_all_ro.

.TP
setsebool -P nfs_export_all_ro 1
.TP
Если вы хотите разрешить доступ на чтение/запись, вы должны установить переключатель nfs_export_all_rw.
.TP
setsebool -P nfs_export_all_rw 1

.TP
Если вы хотите использовать удаленный NFS сервер для хранения домашних директорий этой машины,
то вы должны установить переключатель use_nfs_home_dir boolean.
.TP
setsebool -P use_nfs_home_dirs 1
.TP
Для управления настройками SELinux существует графическая утилита
system-config-selinux.
.SH АВТОРЫ	
Эту страницу руководства написал Dan Walsh <dwalsh@redhat.com>.
Перевод руководства - Андрей Маркелов <andrey@markelov.net>, 2007г.

.SH "СМОТРИ ТАКЖЕ"
selinux(8), chcon(1), setsebool(8)
