.TH  "ypbind_selinux"  "8"  "17 Янв 2005" "dwalsh@redhat.com" "ypbind Selinux Policy documentation"
.SH "НАЗВАНИЕ"
ypbind_selinux \- Политика Security Enhanced Linux для NIS.
.SH "ОПИСАНИЕ"

Security-Enhanced Linux защищает систему при помощи гибко настраиваемого мандатного контроля доступа. По умолчанию работа NIS запрещена. Это является следствием того, что демоны NIS требуют слишком обширного доступа к сети.  
.SH ПЕРЕКЛЮЧАТЕЛИ (BOOLEANS)
.TP
Для того, чтобы система могла работать в окружении NIS, вы должны установить переключатель allow_ypbind.
.TP
setsebool -P allow_ypbind 1
.TP
Для управления настройками SELinux существует графическая утилита system-config-selinux.
.SH АВТОРЫ	
Эту страницу руководства написал Dan Walsh <dwalsh@redhat.com>.
Перевод руководства - Андрей Маркелов <andrey@markelov.net>, 2007г.

.SH "СМОТРИ ТАКЖЕ"
selinux(8), ypbind(8), chcon(1), setsebool(8)
