#!/bin/sh

# this file exists because this line is
# too hard to escape correctly in a makefile

if test -f $1; then
	awk -F = '/^[[:blank:]]*[[:alpha:]]+/{ gsub(/[[:blank:]]*/,"") ; print "define(`"$1"_conf'\'',`"$2"'\'')" }' $1
fi
