.TH "matchpathcon" "8" "21 April 2005" "dwalsh@redhat.com" "SE Linux Command Line documentation"
.SH "NAME"
matchpathcon \- get the default security context for the specified path from the file contexts configuration.

.SH "SYNOPSIS"
.B matchpathcon [-n] filepath...

.SH "DESCRIPTION"
.B matchpathcon
Prints the file path and the default security context associated with it.
.br
If the -n option is given, do not display path.

.SH AUTHOR	
This manual page was written by Dan Walsh <dwalsh@redhat.com>.

.SH "SEE ALSO"
.BR mathpathcon "(3), " 
