name: Global variables

# This is hacky, since GitHub Actions doesn't allow for setting workflow input
# values from a global env block in tests.yml.

env:
  # Minimum versions to build refpolicy.
  PYTHON_VERSION: "3.10"
  SELINUX_USERSPACE_VERSION: "3.9"
  # branch for sechecker
  SECHECKER_VERSION: "4.5"
  # branch for selint
  SELINT_VERSION: "v1.5.0"

  USERSPACE_ARTIFACT_NAME: "selinux-userspace.tar.gz"
  SETOOLS_ARTIFACT_NAME: "setools.whl"

on:
  workflow_call:
    outputs:
      python-version:
        description: "Python version to use"
        value: ${{ jobs.populate.outputs.python-version }}
      selinux-userspace-version:
        description: "SELinux userspace version"
        value: ${{ jobs.populate.outputs.selinux-userspace-version }}
      sechecker-version:
        description: "SETools/sechecker version"
        value: ${{ jobs.populate.outputs.sechecker-version }}
      selint-version:
        description: "selint version"
        value: ${{ jobs.populate.outputs.selint-version }}
      userspace-artifact-name:
        description: "Name of the userspace artifact"
        value: ${{ jobs.populate.outputs.userspace-artifact-name }}
      setools-artifact-name:
        description: "Name of the setools artifact"
        value: ${{ jobs.populate.outputs.setools-artifact-name }}
      build-matrix:
        description: "Full build matrix for policy builds"
        value: ${{ jobs.populate.outputs.build-matrix }}
      analysis-matrix:
        description: "Reduced matrix for validation and diff analysis"
        value: ${{ jobs.populate.outputs.analysis-matrix }}

jobs:
  populate:
    runs-on: ubuntu-latest

    outputs:
      python-version: ${{ steps.set.outputs.python-version }}
      selinux-userspace-version: ${{ steps.set.outputs.selinux-userspace-version }}
      sechecker-version: ${{ steps.set.outputs.sechecker-version }}
      selint-version: ${{ steps.set.outputs.selint-version }}
      userspace-artifact-name: ${{ steps.set.outputs.userspace-artifact-name }}
      setools-artifact-name: ${{ steps.set.outputs.setools-artifact-name }}
      build-matrix: ${{ steps.set.outputs.build-matrix }}
      analysis-matrix: ${{ steps.set.outputs.analysis-matrix }}

    steps:
      - id: set
        shell: bash
        run: |
          echo "python-version=$PYTHON_VERSION" >> $GITHUB_OUTPUT
          echo "selinux-userspace-version=$SELINUX_USERSPACE_VERSION" >> $GITHUB_OUTPUT
          echo "sechecker-version=$SECHECKER_VERSION" >> $GITHUB_OUTPUT
          echo "selint-version=$SELINT_VERSION" >> $GITHUB_OUTPUT
          echo "userspace-artifact-name=$USERSPACE_ARTIFACT_NAME" >> $GITHUB_OUTPUT
          echo "setools-artifact-name=$SETOOLS_ARTIFACT_NAME" >> $GITHUB_OUTPUT
          build_matrix='{
            "distro": ["redhat", "debian", "gentoo"],
            "type": ["standard", "mcs", "mls"],
            "monolithic": ["y", "n"],
            "systemd": ["y", "n"],
            "direct_initrc": ["y", "n"],
            "apps-off": ["unconfined", ""],
            "exclude": [
              {"distro": "redhat", "systemd": "n"},
              {"distro": "redhat", "direct_initrc": "y"},
              {"distro": "debian", "systemd": "n"},
              {"distro": "debian", "direct_initrc": "y"},
              {"type": "mls", "apps-off": ""},
              {"systemd": "y", "direct_initrc": "y"}
            ]
          }'
          echo "build-matrix=$(echo $build_matrix | jq -c .)" >> $GITHUB_OUTPUT

          # remove duplicate analyses
          analysis_extra_excludes='[
            {"monolithic": "n"},
            {"type": "standard"},
            {"apps-off": ""},
            {"systemd": "n"}
          ]'
          analysis_matrix=$(echo "$build_matrix" | jq -c --argjson extra "$analysis_extra_excludes" '.exclude += $extra')
          echo "analysis-matrix=$analysis_matrix" >> $GITHUB_OUTPUT
