name: Build tests

on: [push, pull_request, workflow_dispatch]

jobs:
  global_vars:
    uses: ./.github/workflows/global-vars.yml

  lint_branch_policy:
    uses: ./.github/workflows/lint-policy.yml
    needs: global_vars
    with:
      python-version: ${{ needs.global_vars.outputs.python-version }}
      selint-version: ${{ needs.global_vars.outputs.selint-version }}

  build_userspace:
    uses: ./.github/workflows/build-userspace.yml
    needs: global_vars
    with:
      version: ${{ needs.global_vars.outputs.selinux-userspace-version }}
      python-version: ${{ needs.global_vars.outputs.python-version }}
      ruby-version: ${{ needs.global_vars.outputs.ruby-version }}
      artifact-name: ${{ needs.global_vars.outputs.userspace-artifact-name }}

  build_setools:
    uses: ./.github/workflows/build-setools.yml
    needs: [build_userspace, global_vars]
    with:
      version: ${{ needs.global_vars.outputs.sechecker-version }}
      python-version: ${{ needs.global_vars.outputs.python-version }}
      artifact-name: ${{ needs.global_vars.outputs.setools-artifact-name }}
      userspace-artifact-name: ${{ needs.global_vars.outputs.userspace-artifact-name }}

  build_branch_policy:
    uses: ./.github/workflows/build-policy.yml
    needs: [lint_branch_policy, build_setools, build_userspace, global_vars]
    with:
      python-version: ${{ needs.global_vars.outputs.python-version }}
      userspace-artifact-name: ${{ needs.global_vars.outputs.userspace-artifact-name }}
      setools-artifact-name: ${{ needs.global_vars.outputs.setools-artifact-name }}
      matrix: ${{ needs.global_vars.outputs.build-matrix }}

  validate_branch_policy:
    uses: ./.github/workflows/validate-policy.yml
    needs: [build_branch_policy, build_setools, build_userspace, global_vars]
    with:
      python-version: ${{ needs.global_vars.outputs.python-version }}
      userspace-artifact-name: ${{ needs.global_vars.outputs.userspace-artifact-name }}
      setools-artifact-name: ${{ needs.global_vars.outputs.setools-artifact-name }}
      matrix: ${{ needs.global_vars.outputs.analysis-matrix }}

  build_PRtarget_policy:
    uses: ./.github/workflows/build-policy.yml
    needs: [lint_branch_policy, build_setools, build_userspace, global_vars]
    if: ${{ github.event_name == 'pull_request' }}
    with:
      version: ${{ github.base_ref }}
      artifact-name: "PRbase"
      python-version: ${{ needs.global_vars.outputs.python-version }}
      userspace-artifact-name: ${{ needs.global_vars.outputs.userspace-artifact-name }}
      setools-artifact-name: ${{ needs.global_vars.outputs.setools-artifact-name }}
      matrix: ${{ needs.global_vars.outputs.build-matrix }}

  diff_policy:
    uses: ./.github/workflows/diff-policy.yml
    needs: [build_branch_policy, build_PRtarget_policy, build_setools, build_userspace, global_vars]
    if: ${{ github.event_name == 'pull_request' }}
    with:
      left: "PRbase"
      right: "refpolicy"
      python-version: ${{ needs.global_vars.outputs.python-version }}
      userspace-artifact-name: ${{ needs.global_vars.outputs.userspace-artifact-name }}
      setools-artifact-name: ${{ needs.global_vars.outputs.setools-artifact-name }}
      matrix: ${{ needs.global_vars.outputs.analysis-matrix }}
