name: Validate policy

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version to use"
        required: true
        type: string
      userspace-artifact-name:
        description: "Name of the userspace artifact to download"
        required: true
        type: string
      setools-artifact-name:
        description: "Name of the setools artifact to download"
        required: true
        type: string

jobs:
  sechecker:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        distro: ["redhat", "debian", "gentoo"]
        type: ["standard", "mcs", "mls"]
        monolithic: ["y", "n"]
        systemd: ["y", "n"]
        direct_initrc: ["y", "n"]
        apps-off: ["unconfined", ""]
        exclude:
          - { distro: "redhat", systemd: "n" }
          - { distro: "redhat", direct_initrc: "y" }
          - { distro: "debian", systemd: "n" }
          - { distro: "debian", direct_initrc: "y" }
          - { type: "mls", apps-off: "" }
          - { systemd: "y", direct_initrc: "y" }
          # above here, the matrix must be the same as in build-policy.yml.
          # below here, remove duplicate analyses
          - { monolithic: "n" }
          - { type: "standard" }
          - { apps-off: "" }
          - { systemd: "n" }

    env:
      OUTPUT_LOG: validation-${{ matrix.distro }}-${{ matrix.type }}-${{ matrix.monolithic }}-${{ matrix.systemd }}-${{ matrix.direct_initrc }}-${{ matrix.apps-off }}.log

    steps:
      - name: Checkout testing dir of repo
        uses: actions/checkout@v6
        with:
          sparse-checkout: testing

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update -q

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "${{ inputs.python-version }}"

      - name: Download userspace artifact
        uses: actions/download-artifact@v8
        id: dl-userspace
        with:
          name: ${{ inputs.userspace-artifact-name }}

      - name: Unpack userspace artifact
        shell: bash
        run: |
          tar -C "${{ steps.dl-userspace.outputs.download-path }}" -zxvf ${{ inputs.userspace-artifact-name }}

      - name: Download policy artifact
        uses: actions/download-artifact@v8
        id: dl-refpolicy
        with:
          name: refpolicy-${{ matrix.distro }}-${{ matrix.type }}-${{ matrix.monolithic }}-${{ matrix.systemd }}-${{ matrix.direct_initrc }}-${{ matrix.apps-off }}

      - name: Download setools artifact
        uses: actions/download-artifact@v8
        id: dl-setools
        with:
          name: ${{ inputs.setools-artifact-name }}

      - name: Install dependencies
        shell: bash
        run: |
          sudo python -m pip install setools*.whl networkx

      - name: Validate security goals with sechecker
        shell: bash
        id: sechecker
        run: |
          sechecker testing/sechecker.ini ${{ steps.dl-refpolicy.outputs.download-path }}/sepolicy | tee ${{ env.OUTPUT_LOG}}
        env:
          LD_LIBRARY_PATH: "${{steps.dl-userspace.outputs.download-path}}/lib:${{steps.dl-userspace.outputs.download-path}}/usr/lib:${LD_LIBRARY_PATH}"

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: ${{ env.OUTPUT_LOG}}
          path: ${{ env.OUTPUT_LOG}}
          archive: false
          if-no-files-found: error

      - name: Upload failed build directory artifact
        if: ${{ failure() && runner.debug }}
        uses: actions/upload-artifact@v7
        with:
          name: failed-validation-${{ matrix.distro }}-${{ matrix.type }}-${{ matrix.monolithic }}-${{ matrix.systemd }}-${{ matrix.direct_initrc }}-${{ matrix.apps-off }}
          path: |
            ${{ github.workspace }}
